import React from "react";
import {
  Microscope, Zap, Package, Shield, Globe,
  RefreshCw, Settings, Handshake,
  Vote, Lock, User, Sparkles,
  Dna, Palette, Siren, Rocket,
  GitBranch, Network,
} from "lucide-react";
import { GradientIcon } from "@/components/shared/GradientIcon";
import type { Role, ChannelType, GovernanceModel, PromptTemplate, ScenarioPreset, Toolkit } from "@/types";

export const ROLES: Role[] = [
  { id: "researcher", label: "Researcher", char: "R", icon: <GradientIcon icon={Microscope} size={16} gradient={["#00e5a0", "#34d399"]} />, color: "#00e5a0" },
  { id: "builder", label: "Builder", char: "B", icon: <GradientIcon icon={Zap} size={16} gradient={["#fbbf24", "#fb923c"]} />, color: "#fbbf24" },
  { id: "curator", label: "Curator", char: "C", icon: <GradientIcon icon={Package} size={16} gradient={["#a78bfa", "#c084fc"]} />, color: "#a78bfa" },
  { id: "validator", label: "Validator", char: "V", icon: <GradientIcon icon={Shield} size={16} gradient={["#38bdf8", "#60a5fa"]} />, color: "#38bdf8" },
  { id: "orchestrator", label: "Orchestrator", char: "O", icon: <GradientIcon icon={Globe} size={16} gradient={["#f472b6", "#fb7185"]} />, color: "#f472b6" },
];

export const CHANNEL_TYPES: ChannelType[] = [
  { id: "data", label: "Data Sync", icon: <GradientIcon icon={RefreshCw} size={14} gradient={["#00e5a0", "#38bdf8"]} /> },
  { id: "task", label: "Task Relay", icon: <GradientIcon icon={Settings} size={14} gradient={["#a78bfa", "#f472b6"]} /> },
  { id: "consensus", label: "Consensus", icon: <GradientIcon icon={Handshake} size={14} gradient={["#fbbf24", "#fb923c"]} /> },
];

export const GOVERNANCE_MODELS: GovernanceModel[] = [
  { id: "majority", label: "Majority Vote", icon: <GradientIcon icon={Vote} size={14} gradient={["#00e5a0", "#38bdf8"]} />, desc: "Simple >50% consensus" },
  { id: "threshold", label: "Threshold Sig", icon: <GradientIcon icon={Lock} size={14} gradient={["#fbbf24", "#fb923c"]} />, desc: "M-of-N multisig required" },
  { id: "delegated", label: "Delegated", icon: <GradientIcon icon={User} size={14} gradient={["#a78bfa", "#c084fc"]} />, desc: "Elected lead with veto" },
  { id: "unanimous", label: "Unanimous", icon: <GradientIcon icon={Sparkles} size={14} gradient={["#f472b6", "#fb7185"]} />, desc: "All members must agree" },
];

export const PROMPT_TEMPLATES: PromptTemplate[] = [
  { label: "Custom", prompt: "" },
  { label: "Data Analyst", prompt: "You analyze datasets, identify patterns, and produce statistical summaries. Prioritize accuracy and cite data sources. Output structured JSON when sharing findings with peers." },
  { label: "Code Reviewer", prompt: "You review code for security vulnerabilities, performance issues, and adherence to best practices. Flag critical issues first. Provide fix suggestions as diffs." },
  { label: "Research Synthesizer", prompt: "You aggregate findings from multiple agent sources, resolve contradictions, and produce unified reports. Weight sources by their validation scores." },
  { label: "Task Coordinator", prompt: "You break down complex objectives into subtasks, assign them based on agent capabilities, track progress, and escalate blockers. Maintain a DAG of task dependencies." },
  { label: "Knowledge Curator", prompt: "You index, tag, and organize shared knowledge across the group. Maintain a semantic graph of concepts. Surface relevant context when agents query the knowledge base." },
];

export const SCENARIO_PRESETS: ScenarioPreset[] = [
  {
    id: "defi-audit",
    label: "DeFi Security Audit",
    icon: <GradientIcon icon={Lock} size={20} gradient={["#38bdf8", "#60a5fa"]} />,
    color: "#38bdf8",
    desc: "A multi-agent team that audits smart contracts, analyzes on-chain data, and produces security reports.",
  },
  {
    id: "research-lab",
    label: "Research Lab",
    icon: <GradientIcon icon={Dna} size={20} gradient={["#00e5a0", "#34d399"]} />,
    color: "#00e5a0",
    desc: "Autonomous research pipeline — literature review, hypothesis generation, experiment design, and peer review.",
  },
  {
    id: "content-studio",
    label: "Content Studio",
    icon: <GradientIcon icon={Palette} size={20} gradient={["#f472b6", "#fb7185"]} />,
    color: "#f472b6",
    desc: "A creative agency mesh for ideation, drafting, editing, fact-checking, and publication.",
  },
  {
    id: "incident-response",
    label: "Incident Response",
    icon: <GradientIcon icon={Siren} size={20} gradient={["#ef4444", "#f87171"]} />,
    color: "#ef4444",
    desc: "Security operations team that triages alerts, investigates threats, coordinates remediation, and writes postmortems.",
  },
  {
    id: "startup-ops",
    label: "Startup Operations",
    icon: <GradientIcon icon={Rocket} size={20} gradient={["#fbbf24", "#fb923c"]} />,
    color: "#fbbf24",
    desc: "CEO, CTO, CFO, and Marketing agents collaborating on strategy, roadmap, budgets, and go-to-market.",
  },
  {
    id: "supply-chain",
    label: "Supply Chain DAO",
    icon: <GradientIcon icon={Package} size={20} gradient={["#a78bfa", "#c084fc"]} />,
    color: "#a78bfa",
    desc: "Decentralized supply chain with procurement, logistics, quality assurance, and compliance agents under threshold governance.",
  },
  {
    id: "cross-org-alliance",
    label: "Cross-Org Alliance",
    icon: <GradientIcon icon={GitBranch} size={20} gradient={["#fbbf24", "#f59e0b"]} />,
    color: "#fbbf24",
    desc: "Multi-network ecosystem: two organizations with separate agent teams bridged together for shared intelligence and coordinated ops.",
  },
  {
    id: "federated-research",
    label: "Federated Research",
    icon: <GradientIcon icon={Network} size={20} gradient={["#38bdf8", "#818cf8"]} />,
    color: "#818cf8",
    desc: "Three bridged networks — data collection, analysis hub, and review board — each with specialized agents, connected by cross-network bridges.",
  },
];

export const NETWORK_COLORS = ["#00e5a0", "#38bdf8", "#f472b6", "#fbbf24", "#a78bfa", "#fb923c", "#34d399", "#ef4444"];

export const GROUP_COLORS = ["#f472b6", "#fb923c", "#34d399", "#60a5fa", "#c084fc", "#fbbf24"];

export const ANTHROPIC_MODELS = [
  { id: "claude-sonnet-4-20250514", label: "Claude Sonnet 4", desc: "Best balance of speed and intelligence", tier: "recommended" },
  { id: "claude-opus-4-20250514", label: "Claude Opus 4", desc: "Most capable model for complex tasks", tier: "premium" },
  { id: "claude-haiku-3-5-20241022", label: "Claude 3.5 Haiku", desc: "Fastest and most affordable", tier: "fast" },
  { id: "claude-3-5-sonnet-20241022", label: "Claude 3.5 Sonnet", desc: "Previous generation balanced model", tier: "standard" },
] as const;

// ── Toolkit Registry ──

export const TOOLKITS: Toolkit[] = [
  // ── Command-group toolkits ──
  {
    id: "agent-management",
    name: "Agent Management",
    description: "Create, configure, monitor, and remove AI agents. Includes health checks, prompt editing, and bulk operations.",
    icon: "Bot",
    color: "#00e5a0",
    gradient: ["#00e5a0", "#34d399"],
    category: "agents",
    status: "available",
    commands: ["create_agent", "ping_agent", "delete_agent", "update_agent_prompt", "list_agents", "enable_toolkit", "disable_toolkit", "list_agent_toolkits", "set_agent_toolkits"],
    tags: ["agent", "workspace", "health", "modification", "toolkit"],
    tools: [],
  },
  {
    id: "infrastructure",
    name: "Infrastructure",
    description: "Build the communication backbone — channels between agents and groups for coordination.",
    icon: "ArrowLeftRight",
    color: "#a78bfa",
    gradient: ["#a78bfa", "#c084fc"],
    category: "infrastructure",
    status: "available",
    commands: ["create_channel", "delete_channel", "edit_channel", "create_group", "delete_group", "toggle_group_member", "list_channels", "list_groups"],
    tags: ["infrastructure", "channel", "group", "modification"],
    tools: [],
  },
  {
    id: "messaging",
    name: "Messaging",
    description: "Send direct messages, broadcast to groups, and query message history across channels.",
    icon: "MessageSquare",
    color: "#fbbf24",
    gradient: ["#fbbf24", "#fb923c"],
    category: "communication",
    status: "available",
    commands: ["send_message", "broadcast_message", "list_messages"],
    tags: ["messaging", "interaction", "group", "query"],
    tools: [],
  },
  {
    id: "ecosystem",
    name: "Networks & Ecosystem",
    description: "Create, list, update, and destroy networks. Manage the multi-network ecosystem topology.",
    icon: "Globe",
    color: "#38bdf8",
    gradient: ["#38bdf8", "#60a5fa"],
    category: "infrastructure",
    status: "available",
    commands: ["create_network", "list_networks", "update_network", "destroy_network", "save_ecosystem", "load_ecosystem", "list_ecosystems", "delete_ecosystem"],
    tags: ["ecosystem", "network", "create", "query", "destroy"],
    tools: [],
  },
  {
    id: "topology",
    name: "Topology & Bridges",
    description: "Create cross-network bridges and inspect the overall mesh topology graph.",
    icon: "Network",
    color: "#818cf8",
    gradient: ["#818cf8", "#a78bfa"],
    category: "infrastructure",
    status: "available",
    commands: ["create_bridge", "delete_bridge", "print_topology"],
    tags: ["topology", "bridge", "query"],
    tools: [],
  },
  {
    id: "data-export",
    name: "Data & Export",
    description: "Export workspace backups, ecosystem snapshots, and individual entities as JSON.",
    icon: "Download",
    color: "#34d399",
    gradient: ["#34d399", "#6ee7b7"],
    category: "data",
    status: "available",
    commands: ["export_full_backup", "export_workspace", "export_ecosystem", "export_data"],
    tags: ["data", "export", "backup", "query"],
    tools: [],
  },
  {
    id: "autonomy",
    name: "Autonomy & Tasks",
    description: "Assign, delegate, and escalate tasks for autonomous agent execution. Run group ideation and propose new agents.",
    icon: "Zap",
    color: "#f97316",
    gradient: ["#f97316", "#fb923c"],
    category: "ai",
    status: "available",
    commands: ["assign_task", "delegate_task", "escalate_task", "task_status", "list_tasks", "group_ideate", "propose_agent", "execute_proposal"],
    tags: ["autonomy", "task", "delegation", "escalation", "ideation", "consensus"],
    tools: [],
  },
  {
    id: "governance",
    name: "Governance",
    description: "Facilitate AI-powered group decisions using configurable governance models (majority, threshold, delegated, unanimous).",
    icon: "Vote",
    color: "#f472b6",
    gradient: ["#f472b6", "#fb7185"],
    category: "ai",
    status: "available",
    commands: ["group_decide"],
    tags: ["governance", "group", "decision", "ai"],
    tools: [],
  },
  {
    id: "artifacts",
    name: "Artifacts",
    description: "Create, edit, tag, delete, list, and search text-based artifacts (Markdown, Code, JSON, Plain Text).",
    icon: "FileText",
    color: "#60a5fa",
    gradient: ["#60a5fa", "#93c5fd"],
    category: "data",
    status: "available",
    commands: ["create_artifact", "edit_artifact", "tag_artifact", "delete_artifact", "list_artifacts", "search_artifacts"],
    tags: ["artifact", "content", "create", "edit", "query", "search"],
    tools: [],
  },
  {
    id: "studio",
    name: "Studio",
    description: "Build multi-step jobs on the Studio canvas — add steps, deliverables, inputs, storage, triggers, and lifecycle commands.",
    icon: "Clapperboard",
    color: "#8b5cf6",
    gradient: ["#8b5cf6", "#a78bfa"],
    category: "automation",
    status: "available",
    commands: [
      "studio_get_state", "studio_set_job_meta", "studio_save_job", "studio_run_job", "studio_load_job",
      "studio_clear_canvas", "studio_create_job", "studio_add_trigger", "studio_remove_trigger",
      "studio_add_deliverable", "studio_remove_deliverable", "studio_add_storage", "studio_remove_storage",
      "studio_add_input", "studio_remove_input", "studio_update_input",
      "studio_add_step", "studio_remove_step", "studio_set_step_args", "studio_add_parallel_group",
      "studio_set_step_condition", "studio_set_input_bindings", "studio_set_output_mappings",
    ],
    tags: ["studio", "job", "step", "deliverable", "trigger", "automation"],
    tools: [],
  },
  {
    id: "jobs",
    name: "Job Queue",
    description: "Manage the execution queue — add, pause, resume, cancel jobs and manage the saved job catalog.",
    icon: "ListChecks",
    color: "#14b8a6",
    gradient: ["#14b8a6", "#2dd4bf"],
    category: "automation",
    status: "available",
    commands: ["queue_new_job", "pause_queue", "resume_queue", "delete_queued_job", "list_queued_jobs", "list_catalog_jobs", "save_job_definition", "delete_job_definition"],
    tags: ["job", "system", "catalog", "query"],
    tools: [],
  },
  {
    id: "image-gen",
    name: "Image Generation",
    description: "Generate AI portraits, badges, and icons via Imagen 4.0. Batch-generate images and manage the image cache.",
    icon: "Image",
    color: "#ec4899",
    gradient: ["#ec4899", "#f472b6"],
    category: "ai",
    status: "available",
    commands: ["generate_image", "generate_all_images", "clear_image_cache", "generate_icon"],
    tags: ["image", "agent", "icon", "maintenance"],
    tools: [],
  },
  {
    id: "system",
    name: "System & Config",
    description: "Configure API keys, select AI models, reset workspace, and perform bulk deletions.",
    icon: "Settings",
    color: "#6b7280",
    gradient: ["#6b7280", "#9ca3af"],
    category: "system",
    status: "available",
    commands: ["set_api_key", "select_ai_model", "reset_workspace", "bulk_delete"],
    tags: ["system", "config", "security", "maintenance", "danger"],
    tools: [],
  },
  {
    id: "workspace-mgmt",
    name: "Workspaces",
    description: "Create, switch, duplicate, and delete workspaces for organizing separate environments.",
    icon: "FolderOpen",
    color: "#f59e0b",
    gradient: ["#f59e0b", "#fbbf24"],
    category: "system",
    status: "available",
    commands: ["create_workspace", "switch_workspace", "delete_workspace", "duplicate_workspace"],
    tags: ["workspace", "system"],
    tools: [],
  },
  {
    id: "architect",
    name: "Architect",
    description: "Generate network designs using the AI Architect and deploy full agent mesh networks.",
    icon: "Sparkles",
    color: "#fbbf24",
    gradient: ["#fbbf24", "#fb923c"],
    category: "ai",
    status: "available",
    commands: ["prompt_architect", "deploy_network"],
    tags: ["architect", "deploy", "provision", "ai"],
    tools: [],
  },
  {
    id: "query",
    name: "Query & Inspect",
    description: "List and inspect agents, groups, channels, and messages across the workspace.",
    icon: "Search",
    color: "#94a3b8",
    gradient: ["#94a3b8", "#cbd5e1"],
    category: "data",
    status: "available",
    commands: ["list_agents", "list_groups", "list_channels", "list_messages"],
    tags: ["query", "agent", "group", "channel", "message"],
    tools: [],
  },
  // ── Capability toolkits (external integrations) ──
  {
    id: "web-crawler",
    name: "Web Crawler",
    description: "Load URLs, crawl web pages, and extract content for analysis, research, and data gathering. Supports single-page fetch, multi-page crawl, and structured content extraction.",
    icon: "Globe",
    color: "#38bdf8",
    gradient: ["#38bdf8", "#60a5fa"],
    category: "data-ingestion",
    status: "available",
    commands: [],
    tags: ["web", "crawl", "fetch", "scrape"],
    tools: [
      {
        id: "fetch_url",
        name: "Fetch URL",
        description: "Load a single URL and extract its text content, metadata, and links.",
        inputSchema: { url: { type: "string", description: "The URL to fetch", required: true }, format: { type: "string", description: "Output format: text, markdown, or html", default: "markdown" } },
      },
      {
        id: "crawl_site",
        name: "Crawl Site",
        description: "Recursively crawl a website starting from a root URL, following links up to a specified depth.",
        inputSchema: { url: { type: "string", description: "Root URL to start crawling", required: true }, maxDepth: { type: "number", description: "Maximum link depth to follow", default: 2 }, maxPages: { type: "number", description: "Maximum pages to crawl", default: 10 } },
      },
      {
        id: "extract_links",
        name: "Extract Links",
        description: "Extract and categorize all links from a web page (internal, external, resources).",
        inputSchema: { url: { type: "string", description: "URL to extract links from", required: true }, filter: { type: "string", description: "Filter pattern for links (regex)", default: "" } },
      },
      {
        id: "screenshot_url",
        name: "Screenshot URL",
        description: "Capture a visual screenshot of a web page for analysis.",
        inputSchema: { url: { type: "string", description: "URL to screenshot", required: true }, viewport: { type: "string", description: "Viewport size: mobile, tablet, desktop", default: "desktop" } },
      },
    ],
  },
  {
    id: "ocr",
    name: "OCR",
    description: "Optical Character Recognition — extract text from images, PDFs, and scanned documents.",
    icon: "ScanText",
    color: "#a78bfa",
    gradient: ["#a78bfa", "#c084fc"],
    category: "media",
    status: "coming-soon",
    commands: [],
    tags: ["ocr", "text", "image", "pdf"],
    tools: [
      { id: "ocr_image", name: "OCR Image", description: "Extract text from an image file." },
      { id: "ocr_pdf", name: "OCR PDF", description: "Extract text from PDF pages." },
    ],
  },
  {
    id: "audio-to-text",
    name: "Audio to Text",
    description: "Transcribe audio files and streams to text with speaker diarization.",
    icon: "AudioLines",
    color: "#fbbf24",
    gradient: ["#fbbf24", "#fb923c"],
    category: "media",
    status: "coming-soon",
    commands: [],
    tags: ["audio", "transcribe", "speech"],
    tools: [
      { id: "transcribe_audio", name: "Transcribe Audio", description: "Convert audio file to text transcription." },
    ],
  },
  {
    id: "video-to-text",
    name: "Video to Text",
    description: "Extract transcripts, frame descriptions, and metadata from video content.",
    icon: "Video",
    color: "#f472b6",
    gradient: ["#f472b6", "#fb7185"],
    category: "media",
    status: "coming-soon",
    commands: [],
    tags: ["video", "transcribe", "frames"],
    tools: [
      { id: "transcribe_video", name: "Transcribe Video", description: "Extract audio transcript from video file." },
      { id: "describe_frames", name: "Describe Frames", description: "Generate text descriptions of key video frames." },
    ],
  },
];
