/**
 * Chat functions — agent-to-agent, user-to-agent, and workspace-level chat.
 * Extracted from services/ai.ts for modularity.
 */

import type { Agent, Message, BridgeMessage, ArchPhase, DeployProgress, MeshConfig } from "@/types";
import { ROLES } from "@/constants";
import { TOOLKITS } from "@/services/toolkits";
import { getToolsForAgent } from "@/services/commands/tools";
import type { CommandContext } from "@/services/commands/types";
import { buildCurrentDateTimeContext } from "./prompts";
import type { WorkspaceContext } from "./prompts";
import { getAgentModel } from "./models";
import {
  getModelProvider,
  buildProviderRequest, parseProviderResponse,
} from "./providers";
import { runChatTurn } from "./runner";
import type { ChatTurnMessage } from "./runner";
import type { StreamCallbacks } from "./streaming";
import {
  buildToolkitUsageGuide,
  JOB_CREATION_PLAYBOOK,
  WORKSPACE_RAG_PLAYBOOK,
} from "./toolUsagePlaybook";
import { prepareWorkspaceTurn } from "./workspaceTurn";
import { agentCognitionService } from "@/toolkits/cognition/service";
import { extractDispatchCandidate, matchesPlotTrigger, parseDispatchEnvelope } from "./subAgentDispatch";

export interface ChatMessage {
  id?: string;
  role: "user" | "assistant";
  content: string;
  /** Chat-agent id that authored this message (e.g. "navigator-bot",
   *  "orchestrator-bot"). Used by the chat UI to tint assistant
   *  bubbles with the agent's banner color scheme. */
  agentId?: string;
  /** Wall-clock time the message was added to its conversation (ms
   *  epoch). Rendered as "Xm ago" in the message header. */
  createdAt?: number;
  stopPrompt?: {
    jobId?: string;
    jobName?: string;
    jobDescription?: string;
  };
  architectCard?: {
    prompt: string;
    phase: ArchPhase;
    preview: MeshConfig | null;
    deployProgress: DeployProgress;
    live?: boolean;
  };
  /** Tool calls the AI made (stored for display) */
  toolCalls?: ToolCallDisplay[];
  /** Job ID(s) associated with this message — renders inline progress */
  jobIds?: string[];
  /** Synthetic notice generated by the workspace (e.g. when the user
   *  manually starts/stops a p2p node). Rendered as an inline banner
   *  in the chat and surfaced to the model as user-role context on
   *  the next turn. */
  systemNotice?: boolean;
}

/** Lightweight representation of a tool call for display in chat */
export interface ToolCallDisplay {
  name: string;
  input: Record<string, unknown>;
  result: unknown;
  error?: string;
  duration_ms: number;
  jobId?: string;
  /** Length (in characters) of streamed assistant text emitted before this
   *  tool call began. Drives chronological interleaving in MessageBubble. */
  textOffset?: number;
  /** Structured dispatch metadata for sub-agent routing cards. */
  subAgentDispatch?: {
    dispatchId?: string;
    via: string;
    target: string;
    messageIds?: string[];
    plotId?: string;
    directive?: string;
    expectedFormat?: string;
    status: "blocked" | "dispatched" | "failed" | "completed";
  };
}

function buildDispatchIntercept(enabledPlots: { id: string }[]) {
  if (enabledPlots.length === 0) return undefined;

  return (name: string, input: Record<string, unknown>) => {
    const dispatch = extractDispatchCandidate(name, input);
    if (!dispatch) return null;

    const envelope = dispatch.envelope;
    if (!dispatch.message.includes("[SUB-AGENT DISPATCH]")) {
      const error = {
        error: "SUBAGENT_DISPATCH_ENVELOPE_REQUIRED",
        message: "Dispatch blocked: include [SUB-AGENT DISPATCH] envelope with dispatch-id, plot, directive, and expected-format fields.",
      };
      return {
        content: JSON.stringify(error),
        isError: true,
        result: error,
        error: error.message,
        subAgentDispatch: {
          dispatchId: envelope.dispatchId,
          via: dispatch.via,
          target: dispatch.target,
          plotId: envelope.plotId,
          directive: envelope.directive,
          expectedFormat: envelope.expectedFormat,
          status: "blocked" as const,
        },
      };
    }

    const matchedPlot = envelope.plotId
      ? enabledPlots.find((plot) => plot.id === envelope.plotId)
      : undefined;
    if (!matchedPlot) {
      const error = {
        error: "SUBAGENT_DISPATCH_PLOT_REQUIRED",
        message: `Dispatch blocked: plot id is missing or unknown. Use one of: ${enabledPlots.map((plot) => plot.id).join(", ")}`,
      };
      return {
        content: JSON.stringify(error),
        isError: true,
        result: error,
        error: error.message,
        subAgentDispatch: {
          dispatchId: envelope.dispatchId,
          via: dispatch.via,
          target: dispatch.target,
          plotId: envelope.plotId,
          directive: envelope.directive,
          expectedFormat: envelope.expectedFormat,
          status: "blocked" as const,
        },
      };
    }

    if (!envelope.dispatchId || envelope.dispatchId.length < 6) {
      const error = {
        error: "SUBAGENT_DISPATCH_ID_REQUIRED",
        message: "Dispatch blocked: dispatch-id is required and must be at least 6 characters.",
      };
      return {
        content: JSON.stringify(error),
        isError: true,
        result: error,
        error: error.message,
        subAgentDispatch: {
          dispatchId: envelope.dispatchId,
          via: dispatch.via,
          target: dispatch.target,
          plotId: envelope.plotId,
          directive: envelope.directive,
          expectedFormat: envelope.expectedFormat,
          status: "blocked" as const,
        },
      };
    }

    if (!envelope.directive || envelope.directive.length < 12) {
      const error = {
        error: "SUBAGENT_DISPATCH_DIRECTIVE_REQUIRED",
        message: "Dispatch blocked: directive is required and must be specific.",
      };
      return {
        content: JSON.stringify(error),
        isError: true,
        result: error,
        error: error.message,
        subAgentDispatch: {
          dispatchId: envelope.dispatchId,
          via: dispatch.via,
          target: dispatch.target,
          plotId: envelope.plotId,
          directive: envelope.directive,
          expectedFormat: envelope.expectedFormat,
          status: "blocked" as const,
        },
      };
    }

    if (!envelope.expectedFormat) {
      const error = {
        error: "SUBAGENT_DISPATCH_RESULT_PATTERN_REQUIRED",
        message: "Dispatch blocked: expected-format is required in the dispatch envelope.",
      };
      return {
        content: JSON.stringify(error),
        isError: true,
        result: error,
        error: error.message,
        subAgentDispatch: {
          dispatchId: envelope.dispatchId,
          via: dispatch.via,
          target: dispatch.target,
          plotId: envelope.plotId,
          directive: envelope.directive,
          expectedFormat: envelope.expectedFormat,
          status: "blocked" as const,
        },
      };
    }

    return null;
  };
}

export async function callAgentAI(
  agent: Agent,
  senderAgent: Agent,
  message: string,
  channelType: string,
  conversationHistory: (Message | BridgeMessage)[],
  crossNetworkCtx?: string,
  commandContext?: CommandContext,
): Promise<string> {
  const model = getAgentModel(agent.id);
  const nowContext = buildCurrentDateTimeContext();
  const dispatchEnvelope = message.includes("[SUB-AGENT DISPATCH]")
    ? parseDispatchEnvelope(message)
    : undefined;
  const subAgentResultProtocol = dispatchEnvelope?.dispatchId
    ? `\nSUB-AGENT RESULT PROTOCOL: This message is a delegated sub-agent dispatch. Your reply MUST begin with:\n[SUB-AGENT RESULT]\ndispatch-id: ${dispatchEnvelope.dispatchId}\nstatus: <completed|failed>\nsummary: <one-line summary>\nThen provide the detailed result body.`
    : "";

  const systemPrompt = [
    `You are "${agent.name}", a ${ROLES.find(r => r.id === agent.role)?.label} agent in a decentralized mesh workspace.`,
    nowContext,
    `Your DID: ${agent.did}`,
    `Communication channel type: ${channelType}`,
    agent.prompt ? `\nYour core directive:\n${agent.prompt}` : "",
    agent.toolkits && agent.toolkits.length > 0
      ? `\nYour enabled toolkits: ${agent.toolkits.map(b => {
          const tk = TOOLKITS.find(t => t.id === b.toolkitId);
          return tk ? `${tk.name} (${tk.commands.length} commands)` : b.toolkitId;
        }).join(", ")}. You can only use commands from these toolkits.`
      : "",
    crossNetworkCtx ? `\nCROSS-NETWORK BRIDGE: This message comes from "${senderAgent.name}" in the "${crossNetworkCtx}" network. You are in a different network. Acknowledge the cross-network context.` : "",
    `\nYou are receiving a message from "${senderAgent.name}" (${ROLES.find(r => r.id === senderAgent.role)?.label}, DID: ${senderAgent.did}).`,
    subAgentResultProtocol,
    `Respond concisely and in-character. Keep responses under 150 words. If you have structured output, use markdown formatting.`,
  ].filter(Boolean).join("\n");

  const messages: { role: string; content: string }[] = [];
  conversationHistory.slice(-6).forEach((m) => {
    messages.push({ role: m.fromId === agent.id ? "assistant" : "user", content: m.content });
    if (m.response && m.fromId !== agent.id) messages.push({ role: "assistant", content: m.response });
  });
  messages.push({ role: "user", content: message });

  const provider = getModelProvider(model);
  const tools = commandContext && (provider === "anthropic" || provider === "openai" || provider === "openrouter")
    ? getToolsForAgent(agent)
    : [];

  try {
    if (tools.length > 0 && commandContext) {
      const result = await runChatTurn(
        {
          model,
          systemPrompt,
          messages: messages as ChatTurnMessage[],
          tools,
          commandContext,
          maxRounds: 6,
          // Per-round budget. Tool-use turns need headroom for preamble +
          // tool args in round 1 AND the post-tool final answer in round 2.
          // 1200 was too tight and produced silent mid-sentence truncation
          // both before and after the tool call.
          maxTokens: 4096,
          stream: false,
        },
      );
      return result.text;
    }

    const req = buildProviderRequest(model, systemPrompt, messages, 2048);
    const response = await fetch(req.url, {
      method: "POST",
      headers: req.headers,
      body: JSON.stringify(req.body),
    });
    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData?.error?.message || `API request failed (${response.status})`);
    }
    const data = await response.json();
    return parseProviderResponse(model, data);
  } catch (err) {
    const baseMsg = err instanceof Error ? err.message : String(err);
    const cause = err instanceof Error ? (err as { cause?: unknown }).cause : undefined;
    let causeMsg: string | undefined;
    if (cause) {
      causeMsg = cause instanceof Error
        ? cause.message
        : typeof cause === "object"
          ? (() => { try { return JSON.stringify(cause); } catch { return String(cause); } })()
          : String(cause);
    }
    const msg = causeMsg && !baseMsg.includes(causeMsg) ? `${baseMsg} — ${causeMsg}` : baseMsg;
    return `[Agent error: ${msg}]`;
  }
}

/**
 * Direct user-to-agent chat. The user is a human operator, not another agent.
 * Uses the agent's system prompt and role to respond in-character.
 *
 * If a CommandContext is supplied, the agent gains tool-use capability scoped to
 * its enabled toolkits, and we run a tool-call loop until the model emits a
 * final text response (or hits the round limit).
 */
export async function chatWithAgent(
  agent: Agent,
  userMessage: string,
  history: ChatMessage[],
  commandContext?: CommandContext,
  onToolCall?: (display: ToolCallDisplay) => void,
): Promise<{ text: string; toolCalls: ToolCallDisplay[] }> {
  return runAgentChatTurn(agent, userMessage, history, commandContext, {
    onToolCallComplete: onToolCall,
    stream: false,
  });
}

/**
 * Streaming variant of {@link chatWithAgent}. Mirrors
 * `streamChatWithWorkspace` so the agent chat UI can render tokens,
 * thinking blocks, and tool calls progressively instead of waiting
 * for the entire turn to complete.
 */
export async function streamChatWithAgent(
  agent: Agent,
  userMessage: string,
  history: ChatMessage[],
  callbacks: StreamCallbacks,
  commandContext?: CommandContext,
): Promise<{ text: string; toolCalls: ToolCallDisplay[] }> {
  return runAgentChatTurn(agent, userMessage, history, commandContext, {
    onToken: callbacks.onToken,
    onToolCallStart: callbacks.onToolCallStart,
    onToolCallComplete: callbacks.onToolCallComplete,
    onRoundEnd: callbacks.onRoundEnd,
    signal: callbacks.signal,
    stream: true,
  });
}

async function runAgentChatTurn(
  agent: Agent,
  userMessage: string,
  history: ChatMessage[],
  commandContext: CommandContext | undefined,
  options: {
    onToken?: (token: string) => void;
    onToolCallStart?: (name: string, input: Record<string, unknown>) => void;
    onToolCallComplete?: (display: ToolCallDisplay) => void;
    onRoundEnd?: (round: number) => void;
    signal?: AbortSignal;
    stream: boolean;
  },
): Promise<{ text: string; toolCalls: ToolCallDisplay[] }> {
  const model = getAgentModel(agent.id);
  const provider = getModelProvider(model);

  const tools = commandContext && (provider === "anthropic" || provider === "openai" || provider === "openrouter")
    ? getToolsForAgent(agent)
    : [];

  const cognitionProfile = agentCognitionService.resolveProfileForAgent(agent);
  const enabledPlots = (cognitionProfile.spec.subAgentPlots || []).filter((plot) => plot.enabled);
  const matchedPlots = enabledPlots.filter((plot) => matchesPlotTrigger(plot, userMessage));
  const dispatchIntercept = buildDispatchIntercept(enabledPlots);
  let hasSuccessfulDispatch = false;

  const handleToolCallComplete = (display: ToolCallDisplay): void => {
    if (display.subAgentDispatch && display.subAgentDispatch.status === "dispatched") {
      hasSuccessfulDispatch = true;
    }
    options.onToolCallComplete?.(display);
  };

  const systemPrompt = buildAgentChatSystemPrompt(agent, tools.length);

  const messages: ChatTurnMessage[] = [
    ...history.slice(-20).map(m => ({ role: m.role, content: m.content })),
    { role: "user" as const, content: userMessage },
  ];

  const result = await runChatTurn(
    {
      model,
      systemPrompt,
      messages,
      tools: tools.length > 0 ? tools : undefined,
      commandContext,
      maxRounds: tools.length > 0 ? 6 : 1,
      // Per-round budget — see callAgentAI for the same rationale.
      maxTokens: 4096,
      stream: options.stream && (provider === "anthropic" || provider === "openai" || provider === "openrouter"),
    },
    {
      onToken: options.onToken,
      onToolCallStart: options.onToolCallStart,
      onToolCallComplete: handleToolCallComplete,
      onRoundEnd: options.onRoundEnd,
      interceptToolCall: dispatchIntercept,
      shouldBlockEndTurn: ({ round }) => {
        if (matchedPlots.length === 0 || hasSuccessfulDispatch) return null;
        const plotIds = matchedPlots.map((plot) => plot.id).join(", ");
        return `Sub-agent dispatch required for matched plot(s): ${plotIds}. Emit one valid dispatch envelope before finalizing (round ${round + 1}).`;
      },
      signal: options.signal,
    },
  );
  return { text: result.text, toolCalls: result.toolCalls };
}

/** Shared system-prompt builder for direct user↔agent chats. */
export function buildAgentChatSystemPrompt(agent: Agent, toolCount: number): string {
  const nowContext = buildCurrentDateTimeContext();
  const role = ROLES.find(r => r.id === agent.role);
  const enabledToolkitIds = (agent.toolkits || []).map(t => t.toolkitId);
  const toolkitPlaybookSection = buildToolkitUsageGuide(enabledToolkitIds, { maxToolkits: 6 });
  const includeRagPlaybook = enabledToolkitIds.includes("workspace-rag");
  const cognitionProtocol = agentCognitionService.renderProtocolForAgent(agent);
  return [
    `You are "${agent.name}", a ${role?.label || agent.role} agent in a decentralized mesh workspace.`,
    nowContext,
    `Your DID: ${agent.did}`,
    agent.prompt ? `\nYour core directive:\n${agent.prompt}` : "",
    agent.toolkits && agent.toolkits.length > 0
      ? `\nYour enabled toolkits: ${agent.toolkits.map(b => {
          const tk = TOOLKITS.find(t => t.id === b.toolkitId);
          return tk ? `${tk.name} (${tk.commands.length} commands)` : b.toolkitId;
        }).join(", ")}. You can only use commands from these toolkits. If you need a capability from a disabled toolkit, ask the operator to enable it.`
      : "",
       toolCount > 0
         ? `\nYou have ${toolCount} tools available. Most operational work should follow a simple job workflow: identify the needed tool, search RAG for commands/context, select the commands, create one flat serial job when possible, execute it, then diagnose/retry if needed. Commands from your bound toolkits ALSO appear as direct tools — prefer those when available.

      You MUST follow the configured cognition protocol on every turn:

      ${cognitionProtocol.text}

If a tool errors or returns unexpected output, the Assess line MUST start with "ERROR:" or "UNEXPECTED:" and Next MUST describe a corrective plan (different args, different command, or ask the user). Re-approach with the new information — do not blindly retry. Never invent tool results. Keep each line under 140 characters.

ANTI-FABRICATION RAIL (CRITICAL): Tools execute ONLY via the structured tool-use channel. Prose like "Running X...", "Calling Y...", "Let me invoke...", "The result shows..." does NOT invoke anything. If you say "Needs tools: yes" you MUST emit a real tool_use block immediately — the system rejects fabricated tool turns and forces a retry. Never fabricate tool output, JSON, or status. If the capability you need isn't in your tools, say so plainly.

Never serialize pseudo tool calls in plain text or XML-like tags (forbidden: <longcat_tool_call>, <tool_call>, <longcat_arg_key>, <longcat_arg_value>, or similar wrappers). Those are treated as narration and do not execute.

Never claim you are unable to emit tool_use, blocked by a guardian, or limited by configuration for tool calling. In this runtime, structured tool calls are supported through the provider channel.

NO NARRATION-ONLY TURNS: Never output intent narration instead of execution (forbidden: "I will...", "next I'll...", "then I'll..."). Either emit one real tool_use immediately or provide a direct final answer with no execution claims.

MANDATORY COMMAND EXECUTION FLOW: when tools are needed, do this sequence exactly:
1) Search workspace RAG for the necessary command IDs/args and context.
2) Create a job with command calls as steps (queue_new_job for multi-step, create_job for one atomic command).
3) Run/queue the job and wait for structured results.
4) Review output/status and then continue or finalize.

COLLECTIVE MEMORY PROTOCOL (default-on unless this agent is explicitly set to dark mode):
- Before planning non-trivial work, call \`recall_collective_memory\` with a focused query to load prior decisions/facts.
- When you produce durable facts, decisions, IDs, endpoint details, or runbook steps, call \`remember_collective_memory\`.
- Tag memories with concise topic tags so other agents can retrieve them.
- If the operator requests isolation/privacy, switch to dark mode using \`set_agent_memory_mode\` with mode \`dark\` and stop writing shared memory.`
      : "",
    toolCount > 0 ? `\n${JOB_CREATION_PLAYBOOK}` : "",
    toolCount > 0 && includeRagPlaybook ? `\n${WORKSPACE_RAG_PLAYBOOK}` : "",
    toolCount > 0 && toolkitPlaybookSection ? `\n${toolkitPlaybookSection}` : "",
    `\nYou are chatting directly with a human operator who manages this workspace.`,
    `Respond concisely and in-character. Keep responses under 200 words. Use markdown formatting when appropriate.`,
  ].filter(Boolean).join("\n");
}

export async function chatWithWorkspace(
  userMessage: string,
  history: ChatMessage[],
  ctx: WorkspaceContext,
  commandContext?: CommandContext,
  toolkitIds?: string[],
): Promise<{ text: string; toolCalls: ToolCallDisplay[] }> {
  const prepared = await prepareWorkspaceTurn(userMessage, history, ctx, commandContext, {
    toolkitIds,
    streamRequested: false,
  });

  const result = await runChatTurn({
    model: prepared.model,
    systemPrompt: prepared.systemPrompt,
    messages: prepared.messages,
    tools: prepared.tools.length > 0 ? prepared.tools : undefined,
    commandContext,
    maxRounds: prepared.maxRounds,
  });
  return { text: result.text, toolCalls: result.toolCalls };
}
